### ISSUE TITLE
Repo missing solution file

### ISSUE THREAD

**Issue by RyanFarley** [Sage/SDataCSharpClientLib#1]
Repository is missing the solution (sln) file, which would be fine if sln files were added to the .gitignore. Anyone who forks and creates the solution file and does a pull request will bring in the solution file. Maybe better to either exclude sln file in .gitignore or include in repo (I'd suggest including two solution files for both VS2008 and VS 2010).

Basically, with project files for both .NET 2.0 and .NET 3.5 in the repo I can understand why the solution file is missing, perhaps it would be a good idea to add it to gitignore?

**Comment by stuartcarnie** [comment]
I only have 2010 right now, so I'll create a 2010 specific version, `CSharpClientLib-2010.sln`.  We'll get someone to create the 2008 version too.

A major reason for us going with distributed version control and GitHub is to encourage community collaboration.  If another peer does a pull from your repository and grabs the .sln, that is okay, as they explicitly asked for it :)  You fix something, peer likes the change and pulls it into their repository.  We very well might be that peer that pulls it back in!

Cheers,

Stu

**Comment by RyanFarley** [comment]
I only have VS2010 as well so a VS2010 only solution is fine with me :-)

**Comment by RyanFarley** [comment]
I added a solution file for VS2010 and VS2008 to my fork and sent a pull request if you want to merge them in. Thanks.
